#!/bin/bash
# This script set your Raspberry Pi as an Access Point with fixed IP on eth0 (192.168.1.10) and wlan0 (192.168.0.1)

clear
echo ""
echo "-------------------------------------------------------"
echo "-------------------------------------------------------"
echo "-------------------------------------------------------"
echo "-- Remove an fixed IP and Access Point -Raspberry Pi --"
echo "-------------------------------------------------------"
echo "------- 42 79 4C 75 63 61 73 52 6F 63 68 61 -----------"
echo "-------------------------------------------------------"
echo "-------------------------------------------------------"

read -r -p "[EN]This script will make changes in your RaspberryPi System, some applications can break, may require you to reinstall the image in your SD card. Are you sure that you wish to continue? [y/N] " confirm

if [[ $confirm =~ ^([yY][eE][sS]|[yY])$ ]]
then
	clear
echo "Stop services..."
	systemctl stop dnsmasq
	systemctl stop hostapd
	
echo "Uninstalling..."
	apt-get -y remove hostapd 
	apt-get -y remove dnsmasq 
	
#deleting config files
echo "Deleting existing config files..."
	rm -rf /etc/dhcpcd.conf
	rm -rf /etc/dnsmasq.conf
	rm -rf /etc/hostapd/hostapd.conf
	rm -rf /etc/default/hostapd
	rm -rf /etc/sysctl.conf
	rm -rf /etc/iptables.ipv4.nat
	rm -rf /etc/rc.local
	
#check and backup .old config files
echo "Backing up .old config files..."

cp /etc/dhcpcd.conf.old /etc/dhcpcd.conf -y
cp /etc/dnsmasq.conf.old /etc/dnsmasq.conf -y
cp /etc/hostapd/hostapd.conf.old /etc/hostapd/hostapd.conf -y
cp /etc/default/hostapd.old /etc/default/hostapd -y
cp /etc/sysctl.conf.old /etc/sysctl.conf -y
cp /etc/iptables.ipv4.nat.old  /etc/iptables.ipv4.nat -y
cp /etc/rc.local.old  /etc/rc.local -y
echo "--------------------- DONE ----------------------------"
clear
echo "-------------------------------------------------------"
echo "-------------------------------------------------------"
echo "-------------------------------------------------------"
echo "--------------------- DONE ----------------------------"
echo "-------------------------------------------------------"
echo "-------------------------------------------------------"
echo "-------------------------------------------------------"
echo "  "
echo "REBOOTING in 10 SECONDS..."
echo "  "
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++++++++++++++ CTRL-C to cancel ++++++++++++++++++++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

	sleep 10
	reboot

	exit 0
fi
	exit 0
